# Generated by Django 5.1.7 on 2025-04-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_inspectionreport_escalation_pendinginspection"),
    ]

    operations = [
        migrations.AddField(
            model_name="inspectionreport",
            name="feel_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="look_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inspectionreport",
            name="sound_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="feel",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="look",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="inspectionreport",
            name="sound",
            field=models.BooleanField(default=True),
        ),
    ]
