# Generated by Django 5.1.7 on 2025-04-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_customuser_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(default="user_default", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
